// Package event defines the canonical event contract shared by the hook CLI,
// the daemon, and the TUI. An Event is a small envelope of fields the
// visualizer owns plus the entire original Claude Code hook payload, kept
// verbatim in Raw so new upstream fields never break us.
package event

import (
	"encoding/json"
	"time"
)

// Event is one captured Claude Code hook invocation.
type Event struct {
	ID         string          `json:"id"`          // generated by the CLI
	CapturedAt time.Time       `json:"captured_at"` // CLI wall-clock at capture
	Seq        int64           `json:"seq"`         // daemon-assigned, per-session monotonic
	HookEvent  string          `json:"hook_event"`  // from hook_event_name
	SessionID  string          `json:"session_id"`
	CWD        string          `json:"cwd,omitempty"`
	ToolName   string          `json:"tool_name,omitempty"`
	Raw        json.RawMessage `json:"raw"` // the entire original hook payload
}

// Parse extracts the canonical fields from a raw Claude Code hook payload and
// preserves the whole payload in Raw. It is deliberately lenient: absent
// fields yield zero values rather than errors. It returns an error only when
// raw is not a valid JSON object. ID, CapturedAt, and Seq are NOT set here —
// the CLI sets ID/CapturedAt, the daemon assigns Seq.
func Parse(raw []byte) (*Event, error) {
	var fields struct {
		HookEventName string `json:"hook_event_name"`
		SessionID     string `json:"session_id"`
		CWD           string `json:"cwd"`
		ToolName      string `json:"tool_name"`
	}
	if err := json.Unmarshal(raw, &fields); err != nil {
		return nil, err
	}
	// Copy raw so later mutation of the caller's slice cannot bleed in.
	rawCopy := make(json.RawMessage, len(raw))
	copy(rawCopy, raw)

	return &Event{
		HookEvent: fields.HookEventName,
		SessionID: fields.SessionID,
		CWD:       fields.CWD,
		ToolName:  fields.ToolName,
		Raw:       rawCopy,
	}, nil
}
